### ISSUE TITLE
help building pls

### ISSUE THREAD

**Issue by ha-noi** [vmlaker/sherlock-cpp#1]
Trying to build on a windows 8.1 x64 system
How do I tell scons where boost is? or where my openCV source is?

I get this:

```
scons bites=../bites
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl "/FoF:\OPENCV dependencies\SherlockC++\bites\src\Averager.obj" /c "F:\OPENCV dependencies\SherlockC++\bites\src\Averager.c
pp" -std=c++11 /nologo "/IF:\OPENCV dependencies\SherlockC++\bites\include"
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
Averager.cpp
F:\VStudio14Pro\VC\INCLUDE\xlocale(341): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Spe
cify /EHsc
f:\opencv dependencies\sherlockc++\bites\include\bites/ConcurrentQueue.hpp(5): fatal error C1083: Cannot open include file: '
boost/thread/mutex.hpp': No such file or directory
scons: *** [F:\OPENCV dependencies\SherlockC++\bites\src\Averager.obj] Error 2
scons: building terminated because of errors.

```
